### ISSUE TITLE
egorm 是否应该关闭掉 gorm 的默认日志

### ISSUE THREAD

**Issue by zcong1993** [gotomicro/ego-component#177]
gorm 默认有个自己的日志模块, 会给标准输出打印日志, 并且功能和 egorm  有些重合(慢日志, record not found 日志). 

是否应当默认关闭 gorm 日志, 或者增加一个配置项?

https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L74
https://gorm.io/docs/logger.html

**Comment by askuy** [comment]
这个提议可以，我们找时间看下，怎么加到配置项里。

**Comment by askuy** [comment]
> gorm 默认有个自己的日志模块, 会给标准输出打印日志, 并且功能和 egorm 有些重合(慢日志, record not found 日志).
> 
> 是否应当默认关闭 gorm 日志, 或者增加一个配置项?
> 
> https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L74 https://gorm.io/docs/logger.html

这个问题已经处理，并且将正确的调试日志行数也打印到debug位置。
egorm迁移到新的仓库地址：https://github.com/ego-component/egorm

**Comment by zcong1993** [comment]
额外问一句, 为什么把 egorm 仓库迁移出去?

**Comment by askuy** [comment]
> 额外问一句, 为什么把 egorm 仓库迁移出去?
之前合在一起，release note不方便阅读。
为了更好的推广，所以后面release要标准点，加单测之类的。

**Comment by zcong1993** [comment]
> > 额外问一句, 为什么把 egorm 仓库迁移出去?
> > 之前合在一起，release note不方便阅读。
> > 为了更好的推广，所以后面release要标准点，加单测之类的。

明白, ego-component 确实很好用
